# Generated by Django 3.0.8 on 2023-02-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
